### ISSUE TITLE
Campaign Donors - Export Function

### ISSUE THREAD

**Issue by ginalooch** [PRX/commit_change#4]
Unable to export 
![screen shot 2015-10-26 at 10 33 26 am](https://cloud.githubusercontent.com/assets/15268585/10731767/50090c06-7bcd-11e5-83cb-57087120d690.png)
![screen shot 2015-10-26 at 10 33 38 am](https://cloud.githubusercontent.com/assets/15268585/10731773/531271b2-7bcd-11e5-90c5-2ecd7e9ce0ef.png)

**Comment by jayrbolton** [comment]
The above error was fixed a few days ago; most recent issue was that it would export donation amounts in cents. The fix for this has been deployed -- expect about 10-15 minutes for it to be live. Sorry about the delay fixing that!
